### ISSUE TITLE
Pallet_payment

### ISSUE THREAD

**Issue by ndkazu** [Fair-Squares/fair-squares#236]
**Motivation**

A replica of [orml_payments](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/payments) that does not include multi-currency. For this reason, the parameter AssetId found in orml-payments won't be used in our version

**ToDO**

- [x] Add/Adapt necessary types for our pallets
- [x] update the runtime
- [x] Add/Adapt necessary functions for our payment needs.
- [x] Add tests
