### ISSUE TITLE
Deliverables Milestone-1

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#63]
## deliverable milestone 1 - W3F grant

- [x] pallets
  - [x] #64
    - [x] code
    - [x] #69
    - [x] documentation. --> [guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md#documentation)
  - [x] #65
    - [x] code
    - [x] unit-testing
    - [x] documentation
- [x] #66
- [x] Article milestone-1 Mahir & Ilhan
- [x] #67
- [x] Dockerfile. + Instructions
- [x] Licensing
- [x] #68
- [x] place to publish ? Medium? Subsocial?  Github ? 
- [x] grants delivery repo:
  - [x] https://github.com/Fair-Squares/Grant-Milestone-Delivery/blob/fs-m1/deliveries/fair_squares-milestone-1.md 
- [x] Update how to run all the tests.

**Comment by ilhanu** [comment]
Everything is done, this can be closed
