### ISSUE TITLE
Pallet-Onboarding

### ISSUE THREAD

**Issue by ndkazu** [Fair-Squares/fair-squares#96]
**Motivation**

_First steps for the pallet construction._

**ToDo**

- [x] Correctly add pallet-unique to the runtime
- [ ] Add pallet_onboarding folder with necessary pallets imports.
- [ ] Add necessary function calls (see https://github.com/Fair-Squares/fair-squares/issues/94)
