### ISSUE TITLE
Milestone 2 - deliverables

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#99]
Deliverables [M2](https://github.com/Fair-Squares/Grants-Program/blob/master/applications/fair_squares.md#milestone-2---onboarding-a-house-asset)

**Documentation / Articles**
- [x] Testing Guide 
- [x] Article
- [x] Inline documentation
- [x] Tutorial M2
- [x] grants delivery:
 https://github.com/Fair-Squares/Grant-Milestone-Delivery/blob/fs-m2/deliveries/fair_squares-milestone-2.md 

**Pallets**

- [x] asset-onboarding-pallet.
  - [x] all functionality in #96 #94 
  - [x] unit testing
  - [x] cross pallet unit testing / integration testing
  - [ ] benchmarks
 
- [x] voting-pallet.
  - [x] all functionality in #94 #98  
  - [x] unit testing
  - [x] cross pallet unit testing / integration testing
  - [ ] benchmarks

**Formatting,Linting, testing**

- [x] cargo-fmt
- [x] cargo-clippy
- [x] test with Polkadot.js

Docs & Spec page

- [ ] Work on the docs page in which we can publish our specification of the development chain and the workings of the blockchain. Also a place to form a decent blog where we can publish ourselves.

**Comment by ilhanu** [comment]
Docs & Spec page not created + benchmarks has not been extensive as previous Milestone
